### ISSUE TITLE
After sign in, redirect to countries#show if user profile already exists

### ISSUE THREAD

**Issue by lxxxvi** [oliveranthony17/migrating_mango#21]
@oliveranthony17 

It would be nice to have an addition to the `after_sign_up_path_for`:

https://github.com/oliveranthony17/migrating_mango/blob/3d2a131ade6dbf20d878011ec0ad5932974ae5ad/app/controllers/users/registrations_controller.rb#L17-L19

if the current_user has no profile yet, then route to the `/users_profile/new` else, route to `/countries/:id`.

**Comment by oliveranthony17** [comment]
SORTED! 🥇 👍

**Comment by oliveranthony17** [comment]
🐔
